UPDATRES

diff --git a/.github/workflows/lightnovelpub.yml b/.github/workflows/lightnovelpub.yml
--- a/.github/workflows/lightnovelpub.yml
+++ b/.github/workflows/lightnovelpub.yml
@@ -56,19 +56,24 @@ jobs:
         # Create variables
         CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
         KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
-        
+
         # Import certificate from secrets
         echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode > $CERTIFICATE_PATH
-        
+
         # Create temporary keychain
-        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
-        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
+        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH || true
+        security default-keychain -s $KEYCHAIN_PATH
         security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
-        
+        security set-keychain-settings -t 3600 -l $KEYCHAIN_PATH
+
         # Import certificate to keychain
-        security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
+        security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH || true
+        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
         security list-keychain -d user -s $KEYCHAIN_PATH
-        
+
+        # Clean up
+        rm -f $CERTIFICATE_PATH
+
     - name: Build App
       run: |
         xcodebuild -project LightNovelPub.xcodeproj \
